import React from 'react'

// Shim icons to satisfy imports; render nothing
const stub = (displayName: string) => {
  const Icon: React.FC<any> = (props) => <span {...props} data-icon={displayName} />
  Icon.displayName = displayName
  return Icon
}

export const AlertCircle = stub('AlertCircle')
export const ArrowBack = stub('ArrowBack')
export const ArrowDownRight = stub('ArrowDownRight')
export const ArrowForward = stub('ArrowForward')
export const ArrowLeftRight = stub('ArrowLeftRight')
export const ArrowRight = stub('ArrowRight')
export const ArrowUpRight = stub('ArrowUpRight')
export const Award = stub('Award')
export const BarChart = stub('BarChart')
export const BarChart2 = stub('BarChart2')
export const BarChart3 = stub('BarChart3')
export const Block = stub('Block')
export const Building = stub('Building')
export const Calendar = stub('Calendar')
export const CalendarToday = stub('CalendarToday')
export const Camera = stub('Camera')
export const Cancel = stub('Cancel')
export const Check = stub('Check')
export const CheckCircle = stub('CheckCircle')
export const CheckCircle2 = stub('CheckCircle2')
export const ChevronDown = stub('ChevronDown')
export const ChevronLeft = stub('ChevronLeft')
export const ChevronRight = stub('ChevronRight')
export const ChevronUp = stub('ChevronUp')
export const Clock = stub('Clock')
export const Close = stub('Close')
export const CloudUpload = stub('CloudUpload')
export const Delete = stub('Delete')
export const DollarSign = stub('DollarSign')
export const Download = stub('Download')
export const Edit = stub('Edit')
export const Eye = stub('Eye')
export const EyeOff = stub('EyeOff')
export const FileDownload = stub('FileDownload')
export const FileText = stub('FileText')
export const Filter = stub('Filter')
export const FilterList = stub('FilterList')
export const Home = stub('Home')
export const Image = stub('Image')
export const Info = stub('Info')
export const Lock = stub('Lock')
export const LockOpen = stub('LockOpen')
export const Mail = stub('Mail')
export const MapPin = stub('MapPin')
export const Menu = stub('Menu')
export const MessageSquare = stub('MessageSquare')
export const MoreVert = stub('MoreVert')
export const Phone = stub('Phone')
export const PieChart = stub('PieChart')
export const Plus = stub('Plus')
export const Refresh = stub('Refresh')
export const RefreshCw = stub('RefreshCw')
export const Save = stub('Save')
export const Search = stub('Search')
export const Settings = stub('Settings')
export const Share2 = stub('Share2')
export const Shield = stub('Shield')
export const Sparkles = stub('Sparkles')
export const Star = stub('Star')
export const Target = stub('Target')
export const ThumbsUp = stub('ThumbsUp')
export const TrendingUp = stub('TrendingUp')
export const Unblock = stub('Unblock')
export const Upload = stub('Upload')
export const User = stub('User')
export const UserPlus = stub('UserPlus')
export const VideoCall = stub('VideoCall')
export const X = stub('X')
export const Zap = stub('Zap')
export const ZoomIn = stub('ZoomIn')
